### ISSUE TITLE
[Tutorial] Theme Aurora need SEO meta in theme config

### ISSUE THREAD

**Issue by casimir-crystal** [Meta-Network/meta-hexo-starter#2]
As described in [the official document](https://aurora.tridiamond.tech/guide/site-meta.html#seo-meta), to add the SEO meta information for this theme, need to set the below items:

![image](https://user-images.githubusercontent.com/68253563/139179629-cde5a280-3600-45b2-a4dc-2ff57380ef04.png)

To achieve this, please create or edit the file `scripts/meta-space-config-filter.js`, for example:

```javascript
const fs = require('hexo-fs');
const { deepMerge } = require('hexo-util');
const path = require('path');

// eslint-disable-next-line no-undef
hexo.extend.filter.register('after_init', async function () {
  const { base_dir, render } = this;

  const metaConfigPath = path.join(base_dir, 'meta-space-config.yml');
  const isExists = await fs.exists(metaConfigPath);
  if (!isExists) return;

  const metaConfig = await render.render({ path: metaConfigPath });
  const { user, site } = metaConfig;
  const auroraConfig = {};

  if (site && user) {
    /* add your code like this assignment */
    auroraConfig.site = {
      author: user.username,
      nick: user.nickname,
      subtitle: site.subtitle,
      description: site.description,
      language: site.language,
      logo: site.avatar,
      avatar: site.avatar,
    }
  }

  this.config.theme_config = deepMerge(this.config.theme_config, auroraConfig);
});
```

You can test if it works with the config file(a file named `meta-space-config.yml` in the project's root directory), for example:

```yaml
# meta-space-config.yml
user:
  username: Remi
  nickname: Remi
site:
  title: Remi's test site
  subtitle: Crystal
  description: This is a Meta Space test site
  keywords:
    - Test
    - Meta Space
    - Hexo
  favicon: https://hexo.io/icon/favicon-196x196.png
  avatar: https://avatars.githubusercontent.com/u/68253563?v=4
  language: zh-CN
  timezone: Asia/Shanghai
  domain: remi-site5.metaspaces.life
```
